version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    restart: unless-stopped
    tty: true
    environment:
      - DB_CONNECTION=pgsql
      - DB_DATABASE=task1
      - DB_USERNAME=aris
      - DB_PASSWORD=password
      - AUTH_TOKEN=OktIGTnlJlvjdzeMcKTlcuTsF
    volumes:
      - .:/var/www
    networks:
      - app-network

  webserver:
    image: nginx:alpine
    container_name: laravel-nginx
    restart: unless-stopped
    tty: true
    ports:
      - "8080:8080"
    volumes:
      - ./docker/nginx/app.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

  db:
    image: postgres
    container_name: laravel-db
    restart: unless-stopped
    tty: true
    environment:
      - POSTGRES_DB=task1
      - POSTGRES_USER=aris
      - POSTGRES_PASSWORD=password
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
