version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app1
    restart: unless-stopped
    tty: true
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=task1
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
    volumes:
      - .:/var/www
    networks:
      - app-network

  webserver:
    image: nginx:alpine
    container_name: laravel-nginx
    restart: unless-stopped
    tty: true
    ports:
      - "8080:8081"
    volumes:
      - ./docker/nginx/app.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

  db:
    image: postgres
    container_name: laravel-db
    restart: unless-stopped
    tty: true
    environment:
      - POSTGRES_DB=task1
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  dbdata:

networks:
  app-network:
    driver: bridge
